<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>ViPER4Windows-RE</AssemblyName>
    <RootNamespace>ViperPc</RootNamespace>
    <StartupObject>ViperPc.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.6.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="features.json" />
    <Content Include="icons/*.svg"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content>
  </ItemGroup>
</Project>
